name: notes_app
description: App for notes.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  # bloc: ^6.0.0
  flutter_bloc: ^8.1.1
  bloc_test: ^9.0.3
  notes_repository:
    path: repositories/notes_repository
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true

