name: notes_repository
description: Repository for saving and getting notes
version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  dio: 3.0.10
  hive: ^1.4.4
  hive_flutter: ^0.3.1
  flutter_secure_storage: ^3.3.5
  crypto: ^2.1.5
  tuple: ^1.0.3
  uuid: ^2.2.2